version: '3'
services:
  php: 
    build: .
    volumes: 
      - './:/var/www/html'
      - ./docker-laravel/apache-config/default.conf:/etc/apache2/sites-enabled/000-default.conf
    working_dir:
      '/var/www/html/public'
    ports:
      - 8080:80
    depends_on:
      mysql:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    volumes: 
      - './:/var/www/html'
      - './docker-laravel/nginx/nginx.conf:/etc/nginx/nginx.conf'
    working_dir:
      '/var/www/html/public'
    ports:
      - 8081:80
    depends_on:
      - php
    environment:
      - NGINX_PORT=80

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mlinciko
      - MYSQL_DATABASE=laravel
    ports:
      - 33061:3306
    healthcheck:
      test: ['CMD', "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      retries: 10

  redis:
    image: redis:alpine3.16
    ports:
     - "6379:6379"
    container_name: redis